-- CONTROL DE ASISTENCIA - SUPABASE
-- Proyecto: wnizcvoisbcqbuccaqpk
-- Ejecuta TODO este archivo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.almacenes (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nombre text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default '',
  permisos jsonb not null default '{"editar":false,"administrar":false,"tabs":["asistencia","historial","reportes","perfil"]}'::jsonb,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.administradores_iniciales (
  email text primary key,
  nombre text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.usuarios_almacenes (
  usuario_id uuid not null references auth.users(id) on delete cascade,
  almacen_id uuid not null references public.almacenes(id) on delete cascade,
  rol text not null default 'lector' check (rol in ('administrador','supervisor','lector')),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  primary key (usuario_id, almacen_id)
);

create table if not exists public.solicitudes_almacen (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  almacen_id uuid not null references public.almacenes(id) on delete cascade,
  estado text not null default 'pendiente' check (estado in ('pendiente','aprobada','rechazada')),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (usuario_id, almacen_id)
);

create table if not exists public.estado_almacen (
  almacen_id uuid not null references public.almacenes(id) on delete cascade,
  clave text not null,
  datos jsonb not null default 'null'::jsonb,
  actualizado_por uuid references auth.users(id) on delete set null,
  actualizado_en timestamptz not null default now(),
  primary key (almacen_id, clave)
);

create table if not exists public.asistencias_almacen (
  almacen_id uuid not null references public.almacenes(id) on delete cascade,
  id text not null,
  propietario_id uuid references auth.users(id) on delete set null,
  fecha date not null,
  dni text not null default '',
  trabajador text not null default '',
  turno_id text not null default '',
  turno text not null default '',
  entrada time,
  salida time,
  horas_trabajadas_minutos integer check (horas_trabajadas_minutos is null or horas_trabajadas_minutos >= 0),
  metodo text,
  metodo_salida text,
  estado_entrada text,
  estado_salida text,
  supervisor text,
  finalizado boolean not null default false,
  cierre_id text,
  minutos_salida_anticipada integer not null default 0 check (minutos_salida_anticipada >= 0),
  datos_extra jsonb not null default '{}'::jsonb,
  actualizado_en timestamptz not null default now(),
  primary key (almacen_id, id)
);

create index if not exists idx_usuarios_almacenes_usuario on public.usuarios_almacenes(usuario_id);
create index if not exists idx_solicitudes_usuario on public.solicitudes_almacen(usuario_id);
create index if not exists idx_asistencias_fecha on public.asistencias_almacen(almacen_id, fecha);
create index if not exists idx_asistencias_dni on public.asistencias_almacen(almacen_id, dni);
create index if not exists idx_asistencias_finalizado on public.asistencias_almacen(almacen_id, finalizado);

insert into public.almacenes (codigo, nombre, activo)
values ('ALM-01', 'Almacén principal', true)
on conflict (codigo) do update set nombre = excluded.nombre, activo = true;

-- IMPORTANTE: cambia estos cuatro correos antes de ejecutar el SQL.
insert into public.administradores_iniciales (email, nombre, activo) values
  ('administrador1@empresa.com', 'Administrador 1', true),
  ('administrador2@empresa.com', 'Administrador 2', true),
  ('administrador3@empresa.com', 'Administrador 3', true),
  ('administrador4@empresa.com', 'Administrador 4', true)
on conflict (email) do update set nombre = excluded.nombre, activo = true;

create or replace function public.es_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.usuarios_almacenes
    where usuario_id = (select auth.uid()) and rol = 'administrador' and activo
  );
$$;

create or replace function public.tiene_acceso_almacen(p_almacen_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.usuarios_almacenes
    where usuario_id = (select auth.uid()) and almacen_id = p_almacen_id and activo
  );
$$;

create or replace function public.puede_editar_almacen(p_almacen_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.usuarios_almacenes
    where usuario_id = (select auth.uid()) and almacen_id = p_almacen_id
      and rol in ('administrador','supervisor') and activo
  );
$$;

revoke all on function public.es_admin() from public;
revoke all on function public.tiene_acceso_almacen(uuid) from public;
revoke all on function public.puede_editar_almacen(uuid) from public;
grant execute on function public.es_admin() to authenticated;
grant execute on function public.tiene_acceso_almacen(uuid) to authenticated;
grant execute on function public.puede_editar_almacen(uuid) to authenticated;

create or replace function public.crear_perfil_nuevo_usuario()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_almacen uuid;
  v_nombre text;
  v_es_admin boolean;
  v_permisos jsonb;
begin
  v_nombre := coalesce(nullif(trim(new.raw_user_meta_data ->> 'nombre'), ''), split_part(new.email, '@', 1));
  select exists (
    select 1 from public.administradores_iniciales
    where lower(email) = lower(new.email) and activo
  ) into v_es_admin;

  v_permisos := case when v_es_admin then
    '{"editar":true,"administrar":true,"tabs":["asistencia","historial","programacion","trabajadores","reportes","ajustes","perfil"]}'::jsonb
  else
    '{"editar":false,"administrar":false,"tabs":["asistencia","historial","reportes","perfil"]}'::jsonb
  end;

  insert into public.perfiles (id, nombre, permisos)
  values (new.id, v_nombre, v_permisos)
  on conflict (id) do update set nombre = excluded.nombre, actualizado_en = now();

  begin
    v_almacen := nullif(new.raw_user_meta_data ->> 'almacen_solicitado_id', '')::uuid;
  exception when invalid_text_representation then v_almacen := null;
  end;
  if v_almacen is null then
    select id into v_almacen from public.almacenes where activo order by creado_en limit 1;
  end if;

  if v_almacen is not null then
    insert into public.usuarios_almacenes (usuario_id, almacen_id, rol, activo)
    values (new.id, v_almacen, case when v_es_admin then 'administrador' else 'lector' end, true)
    on conflict (usuario_id, almacen_id) do update set rol = excluded.rol, activo = true;
  end if;
  return new;
end;
$$;

drop trigger if exists al_crear_usuario on auth.users;
create trigger al_crear_usuario after insert on auth.users
for each row execute function public.crear_perfil_nuevo_usuario();

-- Sincroniza las cuentas que ya existan.
insert into public.perfiles (id, nombre, permisos)
select u.id,
  coalesce(nullif(trim(u.raw_user_meta_data ->> 'nombre'), ''), split_part(u.email, '@', 1)),
  case when exists (
    select 1 from public.administradores_iniciales ai
    where lower(ai.email) = lower(u.email) and ai.activo
  ) then '{"editar":true,"administrar":true,"tabs":["asistencia","historial","programacion","trabajadores","reportes","ajustes","perfil"]}'::jsonb
  else '{"editar":false,"administrar":false,"tabs":["asistencia","historial","reportes","perfil"]}'::jsonb end
from auth.users u
on conflict (id) do update set nombre = excluded.nombre, permisos = excluded.permisos, actualizado_en = now();

insert into public.usuarios_almacenes (usuario_id, almacen_id, rol, activo)
select u.id, a.id,
  case when exists (
    select 1 from public.administradores_iniciales ai
    where lower(ai.email) = lower(u.email) and ai.activo
  ) then 'administrador' else 'lector' end, true
from auth.users u
cross join lateral (select id from public.almacenes where activo order by creado_en limit 1) a
on conflict (usuario_id, almacen_id) do update set rol = excluded.rol, activo = true;

alter table public.almacenes enable row level security;
alter table public.perfiles enable row level security;
alter table public.administradores_iniciales enable row level security;
alter table public.usuarios_almacenes enable row level security;
alter table public.solicitudes_almacen enable row level security;
alter table public.estado_almacen enable row level security;
alter table public.asistencias_almacen enable row level security;

drop policy if exists "almacenes activos visibles" on public.almacenes;
create policy "almacenes activos visibles" on public.almacenes for select to anon, authenticated using (activo);
drop policy if exists "admin gestiona almacenes" on public.almacenes;
create policy "admin gestiona almacenes" on public.almacenes for all to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists "ver perfil" on public.perfiles;
create policy "ver perfil" on public.perfiles for select to authenticated using (id = (select auth.uid()) or public.es_admin());
drop policy if exists "crear perfil propio" on public.perfiles;
create policy "crear perfil propio" on public.perfiles for insert to authenticated with check (id = (select auth.uid()));
drop policy if exists "admin actualiza perfiles" on public.perfiles;
create policy "admin actualiza perfiles" on public.perfiles for update to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists "ver asignaciones" on public.usuarios_almacenes;
create policy "ver asignaciones" on public.usuarios_almacenes for select to authenticated using (usuario_id = (select auth.uid()) or public.es_admin());
drop policy if exists "admin gestiona asignaciones" on public.usuarios_almacenes;
create policy "admin gestiona asignaciones" on public.usuarios_almacenes for all to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists "crear solicitud" on public.solicitudes_almacen;
create policy "crear solicitud" on public.solicitudes_almacen for insert to authenticated with check (usuario_id = (select auth.uid()));
drop policy if exists "ver solicitudes" on public.solicitudes_almacen;
create policy "ver solicitudes" on public.solicitudes_almacen for select to authenticated using (usuario_id = (select auth.uid()) or public.es_admin());
drop policy if exists "admin actualiza solicitudes" on public.solicitudes_almacen;
create policy "admin actualiza solicitudes" on public.solicitudes_almacen for update to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists "leer estado" on public.estado_almacen;
create policy "leer estado" on public.estado_almacen for select to authenticated using (public.tiene_acceso_almacen(almacen_id));
drop policy if exists "editar estado" on public.estado_almacen;
create policy "editar estado" on public.estado_almacen for all to authenticated using (public.puede_editar_almacen(almacen_id)) with check (public.puede_editar_almacen(almacen_id));

drop policy if exists "leer asistencias" on public.asistencias_almacen;
create policy "leer asistencias" on public.asistencias_almacen for select to authenticated using (public.tiene_acceso_almacen(almacen_id));
drop policy if exists "editar asistencias" on public.asistencias_almacen;
create policy "editar asistencias" on public.asistencias_almacen for all to authenticated using (public.puede_editar_almacen(almacen_id)) with check (public.puede_editar_almacen(almacen_id));

grant usage on schema public to anon, authenticated;
grant select on public.almacenes to anon, authenticated;
grant select, insert, update on public.perfiles to authenticated;
grant select, insert, update, delete on public.usuarios_almacenes to authenticated;
grant select, insert, update on public.solicitudes_almacen to authenticated;
grant select, insert, update, delete on public.estado_almacen to authenticated;
grant select, insert, update, delete on public.asistencias_almacen to authenticated;
grant usage, select on all sequences in schema public to authenticated;

select 'CONFIGURACION_COMPLETA' as resultado,
  (select count(*) from public.almacenes) as almacenes,
  (select count(*) from public.administradores_iniciales where activo) as administradores_configurados;
